### ISSUE TITLE
Connexion was reset 

### ISSUE THREAD

**Issue by jgcb00** [paracrawl/corset#12]
Hi,

I am very interested in Corset.
I try to build the docker image with : 
```
git clone https://github.com/paracrawl/corset.git
cd corset
docker-compose up -d
```
I didn't touch the `docker-compose.yaml`

The built went well.
```
WARNING: Image for service dp-back was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating dp-solr     ... done
Creating dp-front    ... done
Creating dp-postgres ... done
Creating dp-back     ... done
```

But now, when I try to go to to the website : [http://localhost:5000](http://localhost:5000)
I get the error from firefox : 
```
The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

I don't know how to solve this
I'm working on ubuntu 18.04

There is also an issue on [corset.nlp](https://corset.paracrawl.eu/), I have a 502 error when I try to access it.

Regards

**Comment by jgcb00** [comment]
Indeed so there seems to be 2 issue : 

In dp-front :
```
Error: Error: '/opt/dp/front/data/logs/gunicorn-error.log' isn't writable [FileNotFoundError(2, 'No such file or directory')]
```

In dp-back : 
```

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 108
>>> 'logfile "/opt/dp/back/data/logs/redis.log"'
Can't open the log file: No such file or directory

Error: Error: '/opt/dp/back/data/logs/gunicorn-api-error.log' isn't writable [FileNotFoundError(2, 'No such file or directory')]

Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
While trying to load the module back.tasks.tasks.celery the following error occurred:
Traceback (most recent call last):
  File "/opt/dp/back/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 53, in convert
    return find_app(value)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/dp/back/__init__.py", line 1, in <module>
    from .config import *
  File "/opt/dp/back/config.py", line 5, in <module>
    class Config:
  File "/opt/dp/back/config.py", line 13, in Config
    db = create_engine(DPDB_URI)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''

```

Both seems to have a similar problem link to gunicorn

**Comment by mbanon** [comment]
Could you check that '/opt/dp/front/data/logs/' exists, and mkdir it in case it doesn't?

**Comment by jgcb00** [comment]
Done ! 
So the folder didn't exist, I created it. Same for the back container now on the front : 
I restarted both containers  
and now I have an error in the : gunicorn-error.log
```
[2022-03-30 12:50:12 +0000] [10] [INFO] Starting gunicorn 20.0.4
[2022-03-30 12:50:12 +0000] [10] [INFO] Listening at: http://0.0.0.0:5000 (10)
[2022-03-30 12:50:12 +0000] [10] [INFO] Using worker: gevent
[2022-03-30 12:50:12 +0000] [11] [INFO] Booting worker with pid: 11
[2022-03-30 12:50:12 +0000] [12] [INFO] Booting worker with pid: 12
[2022-03-30 12:50:12 +0000] [13] [INFO] Booting worker with pid: 13
[2022-03-30 12:50:13 +0000] [14] [INFO] Booting worker with pid: 14
[2022-03-30 12:50:14 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(flask_dance_oauth_id_seq, 16385) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/dp/front/app/__init__.py", line 23, in <module>
    from .blueprints.settings.views import settings_blueprint
  File "/opt/dp/front/app/blueprints/settings/views.py", line 5, in <module>
    from front.app.utils import utils, user_utils
  File "/opt/dp/front/app/__init__.py", line 49, in <module>
    db.create_all()
  File "/opt/dp/front/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/opt/dp/front/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4663, in create_all
    bind._run_visitor(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
    self.traverse_single(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(flask_dance_oauth_id_seq, 16385) already exists.
[SQL: 
CREATE TABLE flask_dance_oauth (
	id SERIAL NOT NULL, 
	provider VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	token JSON NOT NULL, 
	user_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2022-03-30 12:50:14 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/dp/front/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(flask_dance_oauth_id_seq, 16385) already exists.
```
I got these for the several times (the number of workers I suppose)
Then finally : 
```
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2022-03-30 12:50:14 +0000] [11] [INFO] Worker exiting (pid: 11)
[2022-03-30 12:50:14 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-03-30 12:50:14 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-03-30 12:50:15 +0000] [14] [INFO] Worker exiting (pid: 14)
[2022-03-30 12:50:15 +0000] [10] [INFO] Shutting down: Master
[2022-03-30 12:50:15 +0000] [10] [INFO] Reason: Worker failed to boot.
```
So this is for dp-front I'm going to look at dp-back

**Comment by jgcb00** [comment]
So in dp-back : 

in redis.log : 
```
11:C 30 Mar 2022 12:49:57.352 # Can't chdir to '/opt/dp/back/data/redis-data': No such file or directory
```
in gunicorn-api-error.log
```
[2022-03-30 12:49:58 +0000] [21] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/dp/back/api/app/__init__.py", line 7, in <module>
    from back.api.config import Config
  File "/opt/dp/back/__init__.py", line 1, in <module>
    from .config import *
  File "/opt/dp/back/config.py", line 5, in <module>
    class Config:
  File "/opt/dp/back/config.py", line 13, in Config
    db = create_engine(DPDB_URI)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/opt/dp/back/venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''
```
Could it be to the fact that you use python:lastest image instead of a 3.9, version and that might have issue in the newest version of python ?

**Comment by jgcb00** [comment]
For dp-front it seems that I might just have to delete some lines on postgresql (dp-postgres) in a table ?

**Comment by mbanon** [comment]
hmmm Try mkdir  '/opt/dp/back/data/redis-data' 

If it does not work after that, try comenting the line "      - ./postgres-data:/var/lib/postgresql/data" in the dp-postgres part of the docker-compose file.

**Comment by jgcb00** [comment]
also `docker logs dp-solr`
```
Creating /var/solr/data
Cannot write to /var/solr as 8983:8983
drwxr-xr-x 2 root root 4096 Mar 28 12:59 /var/solr
```

**Comment by mbanon** [comment]
> also `docker logs dp-solr`
> 
> ```
> Creating /var/solr/data
> Cannot write to /var/solr as 8983:8983
> drwxr-xr-x 2 root root 4096 Mar 28 12:59 /var/solr
> ```

If you didn't change the docker-compose file, /var/solr is mounted persistent in /mnt/solr-data/solr . Does it exist in your filesystem?

**Comment by jgcb00** [comment]
Yes it does exist

**Comment by jgcb00** [comment]
There seems to be a lot of persission issue, may be I should have run it with sudo docker-compose ?

**Comment by mbanon** [comment]
Yes please, try with sudo.

Then try forcing building (sudo docker-compose build), and then start containers again.

You can also try commenting the volumes part in the docker-compose file, then export those directories out from the container with `sudo docker cp container:path  yourfilesystem/path`, and they uncommenting the volumes in the docker-compose again.

**Comment by mbanon** [comment]
Closing this because of the lack of activity during the last month.

Also, note that  https://corset.paracrawl.eu/ is up again.
